name: ArmorSetEffects
version: 2.2.4
main: hkr.ArmorSetEffectsMain
api-version: 1.17
author: hallis21
commands:
   armor-reload:
      description: Reloads the armor-set config file
      usage: /armor-reload
      permission: armorseteffects.reload
   armor-list:
      description: Shows all non-hidden sets (Unless permitted)
      usage: /armor-list [armor set name]
      permission: armorseteffects.viewsets

permissions:
   armorseteffects.reload:
      description: Allows a player to reload the config file
      default: true
   armorsetsonus.receive:
      description: Allows a player to receive armor set bonuses
      default: true
   armorsetsonus.viewsets:
      description: Allows a player to view sets
      default: true
   armorsetsonus.viewsets.all:
      description: Allows a player to view sets (Even hidden ones)
      default: true
   armorseteffects.viewsets.inspect:
      description: Allows a player to inspect non-hidden sets
      default: true
   armorseteffects.viewsets.inspect.all:
      description: Allows a player to inspect ALL sets
      default: true
   armorseteffects.sets.exOne:
      description: Allows all players to use Example Set 1
      default: true