name: ArmorSetBonus
version: 2.2.1
main: hkr.ArmorSetBonusMain
api-version: 1.15
author: hallis21
commands:
   armor-reload:
      description: Reloads the armor-set config file
      usage: /armor-reload
      permission: armorsetbonus.reload
   armor-list:
      description: Shows all non-hidden sets (Unless permitted)
      usage: /armor-list [armor set name]
      permission: armorsetbonus.viewsets

permissions:
   armorsetbonus.reload:
      description: Allows a player to reload the config file
      default: true
   armorsetsonus.receive:
      description: Allows a player to receive armor set bonuses
      default: true
   armorsetsonus.viewsets:
      description: Allows a player to view sets
      default: true
   armorsetsonus.viewsets.all:
      description: Allows a player to view sets (Even hidden ones)
      default: true
   armorsetbonus.viewsets.inspect:
      description: Allows a player to inspect non-hidden sets
      default: true
   armorsetbonus.viewsets.inspect.all:
      description: Allows a player to inspect ALL sets
      default: true
   armorsetbonus.sets.exOne:
      description: Allows all players to use Example Set 1
      default: true